### ISSUE TITLE
Improve Rxjs imports

### ISSUE THREAD

**Issue by celsomtrindade** [KevCJones/angularx-bootstrap-modal#6]
According to Angular and Rxjs best practices, it's better to import just the objects/operators used.

There are some cases where it's importing things like:

    import { Observable } from "rxjs";

Instead of

    import { Observable } from "rxjs/Observable";

> Note: I'll try to make a PR asap.

**Comment by kevcjones-archived** [comment]
Great,  yeah i've had to do a similiar update to a personal project of my own, PR welcome

**Comment by kevcjones-archived** [comment]
Thanks for this - simple to review. Merged
