### ISSUE TITLE
Background scrolls instead of modal

### ISSUE THREAD

**Issue by artemzakharov** [KevCJones/angularx-bootstrap-modal#7]
When the modal is open, scrolling seems to affect the background only - the background will scroll if it's overflowing, and the modal won't scroll at all, whether it overflows or not. 

This can be fixed by manually using jQuery to add the 'modal-open' class to the body tag like Bootstrap does when a modal is opened, but it would be nice to see this built in to the addDialog function.

**Comment by kevcjones-archived** [comment]
I don't see an issue with the addition, but i have to ask a couple questions because i've got my modal implemented and it scrolls before my background does, so i have a feeling i've either not tested enough browsers or my implementation 'hack' has worked around the issue without knowing. 

```this.dialogService['container'] = document.getElementById('ta');```

I don't see how unless my styles on the dom nodes at the ta level handle the overflow-y for the modal layer. 

I assume this is a consistent issue for you across the common browsers. If you want to do a PR i'll review, otherwise i'll try to carve out some free time to implement this and test it.

**Comment by celsomtrindade** [comment]
I've noticed this behavior as well, where the body doesn't have something to prevent it's scroll and only scroll the modal. But this is easily solved and doesn't need jQuery, simple JS will do.

````
**not tested**

document.body.style.overflowY="hidden"; // When creating dialog
document.body.style.overflowY=null; // When destroying dialog

// or add/remove class
````
> **Note**: It may be necessary to check if the dialog is the last one before removing the style, because I know there is the option to open multiple dialogs at the same time (unless I'm wrong).

> **Note²**: I aso don't think it's a bug, because it's a feature not implemented yet.

> About the scroll problem, I noticed it depends on your mouse position on the screen. If your mouse isn't over the dialog box itself, it will scroll the body instead. If it's over the dialog box, it will scroll the dialog and then the body (considering both have scroll).

**Comment by artemzakharov** [comment]
Mouse position doesn't seem to be a factor in my case - the background scrolls no matter where the mouse is, and the modal doesn't scroll at all. I implemented the module on a fresh project (Javascript Services SPA Angular Template, which uses Angular 4.2.5 and Bootstrap 3.3.7), and the problem persists. I've only tested with Chrome, however.

My proposed solution would be a pool stored in the DialogService (which I assume is a singleton) that keeps track of all open modals, and either disables body scrolling when there's at least one modal in the pool or enables body scrolling when the pool is empty (to account for multiple modals).

I don't think I'll have the time to play around with the module and try to implement this myself, unfortunately, but it's the easiest way I see to solve this.

**Comment by kevcjones-archived** [comment]
@artemzakharov in the end the change was fairly nominal, and the pool already exists in the holder where the add / remove operations take place. The rest of simple enough. I've used classList knowing that even angular ship with the suggestion to use classList.js as a polyfill if you want to use older browsers. I'll give anyone a day or so to review the change, and cry havoc if they see any issues then i'll merge.
